export const TabData = {
  tab1: [
    {
      User: { name: "Sam Altman", email: "samaltman123@gmail.com" },
      "Risk level": "Medium",
      "Trigger reason": "IP Change",
      "In queue for": "4 days",
      "Date added on": "12 Oct, 2023",
      "Previously reviewed": { choice: "Yes", date: "23 Aug, 2023" },
    },
    {
      User: { name: "Sameer Choubey", email: "sammerchoubey123@gmail.com" },
      "Risk level": "High",
      "Trigger reason": "FIFO",
      "In queue for": "4 days",
      "Date added on": "12 Oct, 2023",
      "Previously reviewed": { choice: "No", date: "" },
    },
    {
      User: { name: "Adarsh Panikar", email: "adarsh@onjuno.com" },
      "Risk level": "Low",
      "Trigger reason": "IP Change",
      "In queue for": "5 days",
      "Date added on": "12 Oct, 2023",
      "Previously reviewed": { choice: "No", date: "" },
    },
    {
      User: { name: "Pratik Shetty", email: "pratik3@gmail.com" },
      "Risk level": "High",
      "Trigger reason": "FIFO",
      "In queue for": "5 days",
      "Date added on": "12 Oct, 2023",
      "Previously reviewed": { choice: "Yes", date: "12 Sep, 2023" },
    },
    {
      User: { name: "Elon Musk", email: "elon@twitterceo.com" },
      "Risk level": "Low",
      "Trigger reason": "FIFO",
      "In queue for": "5 days",
      "Date added on": "12 Oct, 2023",
      "Previously reviewed": { choice: "Yes", date: "12 Sep, 2023" },
    },
    {
      User: { name: "Trina Kundu", email: "trina@onjuno.com" },
      "Risk level": "Low",
      "Trigger reason": "FIFO",
      "In queue for": "5 days",
      "Date added on": "12 Oct, 2023",
      "Previously reviewed": { choice: "Yes", date: "12 Sep, 2023" },
    },
  ],

  tab2: [
    {
      User: { name: "Sam Altman", email: "samaltman123@gmail.com" },
      "Risk level": "Medium",
      "Action reason": "Flagged",
      "Time to close": "14 days",
      "Date added on": "12 Oct, 2023",
      "Action taken by": { name: "Neil", email: "neil@onjuno.com" },
    },
    {
      User: { name: "Sameer Choubey", email: "sammerchoubey123@gmail.com" },
      "Risk level": "High",
      "Action reason": "Closed",
      "Time to close": "14 days",
      "Date added on": "12 Oct, 2023",
      "Action taken by": { name: "Pratik", email: "pratik3@onjuno.com" },
    },
    {
      User: { name: "Adarsh Panikar", email: "adarsh@onjuno.com" },
      "Risk level": "Low",
      "Action reason": "Cleared",
      "Time to close": "15 days",
      "Date added on": "12 Oct, 2023",
      "Action taken by": { name: "Prashanth", email: "prashanth@onjuno.com" },
    },
    {
      User: { name: "Pratik Shetty", email: "pratik3@gmail.com" },
      "Risk level": "High",
      "Action reason": "SOI requested",
      "Time to close": "15 days",
      "Date added on": "12 Oct, 2023",
      "Action taken by": { name: "Rasleen kaur", email: "rasleen@onjuno.com" },
    },
    {
      User: { name: "Elon Musk", email: "elon@twitterceo.com" },
      "Risk level": "Low",
      "Action reason": "Flagged",
      "Time to close": "15 days",
      "Date added on": "12 Oct, 2023",
      "Action taken by": {
        name: "Pratiik Shetty",
        email: "pratikc3@onjuno.com",
      },
    },
    {
      User: { name: "Trina Kundu", email: "trina@onjuno.com" },
      "Risk level": "Low",
      "Action reason": "Closed",
      "Time to close": "15 days",
      "Date added on": "12 Oct, 2023",
      "Action taken by": { name: "Varun Deshpande", email: "varun@onjuno.com" },
    },
  ],
};

export const TabHeadings = {
  tab1: [
    "User",
    "Risk level",
    "Trigger reason",
    "In queue for",
    "Date added on",
    "Previously reviewed",
  ],
  tab2: [
    "User",
    "Risk level",
    "Action reason",
    "Time to close",
    "Date added on",
    "Action taken by",
  ],
};
